list_of_items = ["whiskey",
"marshmallows",
"papayas",
"rice wine",
"ice cream",
"pineapples",
"pinto beans",
"chicken",
"pesto",
"pico de gallo",
"black olives",
"milkrice",
"wheat",
"car wash",
"notebooks purchase",
"gym"]
